// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/gophkeeper.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CertType int32

const (
	CertType_UNKNOWN CertType = 0
	CertType_CA      CertType = 1
	CertType_SERVER  CertType = 2
	CertType_CLIENT  CertType = 3
)

// Enum value maps for CertType.
var (
	CertType_name = map[int32]string{
		0: "UNKNOWN",
		1: "CA",
		2: "SERVER",
		3: "CLIENT",
	}
	CertType_value = map[string]int32{
		"UNKNOWN": 0,
		"CA":      1,
		"SERVER":  2,
		"CLIENT":  3,
	}
)

func (x CertType) Enum() *CertType {
	p := new(CertType)
	*p = x
	return p
}

func (x CertType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CertType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_gophkeeper_proto_enumTypes[0].Descriptor()
}

func (CertType) Type() protoreflect.EnumType {
	return &file_proto_gophkeeper_proto_enumTypes[0]
}

func (x CertType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CertType.Descriptor instead.
func (CertType) EnumDescriptor() ([]byte, []int) {
	return file_proto_gophkeeper_proto_rawDescGZIP(), []int{0}
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CertRequest   []byte                 `protobuf:"bytes,1,opt,name=cert_request,json=certRequest" json:"cert_request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_gophkeeper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_gophkeeper_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetCertRequest() []byte {
	if x != nil {
		return x.CertRequest
	}
	return nil
}

type RegisterResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Ok                *bool                  `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
	CaCertificate     []byte                 `protobuf:"bytes,2,opt,name=ca_certificate,json=caCertificate" json:"ca_certificate,omitempty"`
	ClientCertificate []byte                 `protobuf:"bytes,3,opt,name=client_certificate,json=clientCertificate" json:"client_certificate,omitempty"`
	Error             *string                `protobuf:"bytes,4,opt,name=error" json:"error,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_gophkeeper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_gophkeeper_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetOk() bool {
	if x != nil && x.Ok != nil {
		return *x.Ok
	}
	return false
}

func (x *RegisterResponse) GetCaCertificate() []byte {
	if x != nil {
		return x.CaCertificate
	}
	return nil
}

func (x *RegisterResponse) GetClientCertificate() []byte {
	if x != nil {
		return x.ClientCertificate
	}
	return nil
}

func (x *RegisterResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Passwords     [][]byte               `protobuf:"bytes,1,rep,name=passwords" json:"passwords,omitempty"`
	Texts         [][]byte               `protobuf:"bytes,2,rep,name=texts" json:"texts,omitempty"`
	Bins          [][]byte               `protobuf:"bytes,3,rep,name=bins" json:"bins,omitempty"`
	Banks         [][]byte               `protobuf:"bytes,4,rep,name=banks" json:"banks,omitempty"`
	Error         *string                `protobuf:"bytes,5,opt,name=error" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_proto_gophkeeper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_proto_gophkeeper_proto_rawDescGZIP(), []int{2}
}

func (x *ListResponse) GetPasswords() [][]byte {
	if x != nil {
		return x.Passwords
	}
	return nil
}

func (x *ListResponse) GetTexts() [][]byte {
	if x != nil {
		return x.Texts
	}
	return nil
}

func (x *ListResponse) GetBins() [][]byte {
	if x != nil {
		return x.Bins
	}
	return nil
}

func (x *ListResponse) GetBanks() [][]byte {
	if x != nil {
		return x.Banks
	}
	return nil
}

func (x *ListResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

var File_proto_gophkeeper_proto protoreflect.FileDescriptor

const file_proto_gophkeeper_proto_rawDesc = "" +
	"\n" +
	"\x16proto/gophkeeper.proto\x12\n" +
	"gophkeeper\x1a\x1bgoogle/protobuf/empty.proto\"4\n" +
	"\x0fRegisterRequest\x12!\n" +
	"\fcert_request\x18\x01 \x01(\fR\vcertRequest\"\x8e\x01\n" +
	"\x10RegisterResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12%\n" +
	"\x0eca_certificate\x18\x02 \x01(\fR\rcaCertificate\x12-\n" +
	"\x12client_certificate\x18\x03 \x01(\fR\x11clientCertificate\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\x82\x01\n" +
	"\fListResponse\x12\x1c\n" +
	"\tpasswords\x18\x01 \x03(\fR\tpasswords\x12\x14\n" +
	"\x05texts\x18\x02 \x03(\fR\x05texts\x12\x12\n" +
	"\x04bins\x18\x03 \x03(\fR\x04bins\x12\x14\n" +
	"\x05banks\x18\x04 \x03(\fR\x05banks\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error*7\n" +
	"\bCertType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x06\n" +
	"\x02CA\x10\x01\x12\n" +
	"\n" +
	"\x06SERVER\x10\x02\x12\n" +
	"\n" +
	"\x06CLIENT\x10\x032O\n" +
	"\x06Public\x12E\n" +
	"\bRegister\x12\x1b.gophkeeper.RegisterRequest\x1a\x1c.gophkeeper.RegisterResponse2C\n" +
	"\aPrivate\x128\n" +
	"\x04List\x12\x16.google.protobuf.Empty\x1a\x18.gophkeeper.ListResponseB\x12Z\x10gophkeeper/protob\beditionsp\xe8\a"

var (
	file_proto_gophkeeper_proto_rawDescOnce sync.Once
	file_proto_gophkeeper_proto_rawDescData []byte
)

func file_proto_gophkeeper_proto_rawDescGZIP() []byte {
	file_proto_gophkeeper_proto_rawDescOnce.Do(func() {
		file_proto_gophkeeper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gophkeeper_proto_rawDesc), len(file_proto_gophkeeper_proto_rawDesc)))
	})
	return file_proto_gophkeeper_proto_rawDescData
}

var file_proto_gophkeeper_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_gophkeeper_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_gophkeeper_proto_goTypes = []any{
	(CertType)(0),            // 0: gophkeeper.CertType
	(*RegisterRequest)(nil),  // 1: gophkeeper.RegisterRequest
	(*RegisterResponse)(nil), // 2: gophkeeper.RegisterResponse
	(*ListResponse)(nil),     // 3: gophkeeper.ListResponse
	(*emptypb.Empty)(nil),    // 4: google.protobuf.Empty
}
var file_proto_gophkeeper_proto_depIdxs = []int32{
	1, // 0: gophkeeper.Public.Register:input_type -> gophkeeper.RegisterRequest
	4, // 1: gophkeeper.Private.List:input_type -> google.protobuf.Empty
	2, // 2: gophkeeper.Public.Register:output_type -> gophkeeper.RegisterResponse
	3, // 3: gophkeeper.Private.List:output_type -> gophkeeper.ListResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_gophkeeper_proto_init() }
func file_proto_gophkeeper_proto_init() {
	if File_proto_gophkeeper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gophkeeper_proto_rawDesc), len(file_proto_gophkeeper_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_gophkeeper_proto_goTypes,
		DependencyIndexes: file_proto_gophkeeper_proto_depIdxs,
		EnumInfos:         file_proto_gophkeeper_proto_enumTypes,
		MessageInfos:      file_proto_gophkeeper_proto_msgTypes,
	}.Build()
	File_proto_gophkeeper_proto = out.File
	file_proto_gophkeeper_proto_goTypes = nil
	file_proto_gophkeeper_proto_depIdxs = nil
}
