// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/gophkeeper.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecordType int32

const (
	RecordType_UNKNOWN  RecordType = 0
	RecordType_PASSWORD RecordType = 1
	RecordType_TEXT     RecordType = 2
	RecordType_BIN      RecordType = 3
	RecordType_BANK     RecordType = 4
)

// Enum value maps for RecordType.
var (
	RecordType_name = map[int32]string{
		0: "UNKNOWN",
		1: "PASSWORD",
		2: "TEXT",
		3: "BIN",
		4: "BANK",
	}
	RecordType_value = map[string]int32{
		"UNKNOWN":  0,
		"PASSWORD": 1,
		"TEXT":     2,
		"BIN":      3,
		"BANK":     4,
	}
)

func (x RecordType) Enum() *RecordType {
	p := new(RecordType)
	*p = x
	return p
}

func (x RecordType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecordType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_gophkeeper_proto_enumTypes[0].Descriptor()
}

func (RecordType) Type() protoreflect.EnumType {
	return &file_proto_gophkeeper_proto_enumTypes[0]
}

func (x RecordType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RecordType.Descriptor instead.
func (RecordType) EnumDescriptor() ([]byte, []int) {
	return file_proto_gophkeeper_proto_rawDescGZIP(), []int{0}
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CertRequest   []byte                 `protobuf:"bytes,1,opt,name=cert_request,json=certRequest" json:"cert_request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_gophkeeper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_gophkeeper_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetCertRequest() []byte {
	if x != nil {
		return x.CertRequest
	}
	return nil
}

type RegisterResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CaCertificate     []byte                 `protobuf:"bytes,2,opt,name=ca_certificate,json=caCertificate" json:"ca_certificate,omitempty"`
	ClientCertificate []byte                 `protobuf:"bytes,3,opt,name=client_certificate,json=clientCertificate" json:"client_certificate,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_gophkeeper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_gophkeeper_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetCaCertificate() []byte {
	if x != nil {
		return x.CaCertificate
	}
	return nil
}

func (x *RegisterResponse) GetClientCertificate() []byte {
	if x != nil {
		return x.ClientCertificate
	}
	return nil
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *RecordType            `protobuf:"varint,1,opt,name=type,enum=gophkeeper.RecordType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_proto_gophkeeper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_proto_gophkeeper_proto_rawDescGZIP(), []int{2}
}

func (x *ListRequest) GetType() RecordType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return RecordType_UNKNOWN
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []byte                 `protobuf:"bytes,1,opt,name=records" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_proto_gophkeeper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_proto_gophkeeper_proto_rawDescGZIP(), []int{3}
}

func (x *ListResponse) GetRecords() []byte {
	if x != nil {
		return x.Records
	}
	return nil
}

type AddRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *RecordType            `protobuf:"varint,1,opt,name=type,enum=gophkeeper.RecordType" json:"type,omitempty"`
	Record        []byte                 `protobuf:"bytes,2,opt,name=record" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRecordRequest) Reset() {
	*x = AddRecordRequest{}
	mi := &file_proto_gophkeeper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRecordRequest) ProtoMessage() {}

func (x *AddRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRecordRequest.ProtoReflect.Descriptor instead.
func (*AddRecordRequest) Descriptor() ([]byte, []int) {
	return file_proto_gophkeeper_proto_rawDescGZIP(), []int{4}
}

func (x *AddRecordRequest) GetType() RecordType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return RecordType_UNKNOWN
}

func (x *AddRecordRequest) GetRecord() []byte {
	if x != nil {
		return x.Record
	}
	return nil
}

type GetRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *RecordType            `protobuf:"varint,1,opt,name=type,enum=gophkeeper.RecordType" json:"type,omitempty"`
	RecordNumber  *int64                 `protobuf:"varint,2,opt,name=record_number,json=recordNumber" json:"record_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecordRequest) Reset() {
	*x = GetRecordRequest{}
	mi := &file_proto_gophkeeper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecordRequest) ProtoMessage() {}

func (x *GetRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecordRequest.ProtoReflect.Descriptor instead.
func (*GetRecordRequest) Descriptor() ([]byte, []int) {
	return file_proto_gophkeeper_proto_rawDescGZIP(), []int{5}
}

func (x *GetRecordRequest) GetType() RecordType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return RecordType_UNKNOWN
}

func (x *GetRecordRequest) GetRecordNumber() int64 {
	if x != nil && x.RecordNumber != nil {
		return *x.RecordNumber
	}
	return 0
}

type GetRecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *RecordType            `protobuf:"varint,1,opt,name=type,enum=gophkeeper.RecordType" json:"type,omitempty"`
	Record        []byte                 `protobuf:"bytes,2,opt,name=record" json:"record,omitempty"`
	Error         *string                `protobuf:"bytes,3,opt,name=error" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecordResponse) Reset() {
	*x = GetRecordResponse{}
	mi := &file_proto_gophkeeper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecordResponse) ProtoMessage() {}

func (x *GetRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecordResponse.ProtoReflect.Descriptor instead.
func (*GetRecordResponse) Descriptor() ([]byte, []int) {
	return file_proto_gophkeeper_proto_rawDescGZIP(), []int{6}
}

func (x *GetRecordResponse) GetType() RecordType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return RecordType_UNKNOWN
}

func (x *GetRecordResponse) GetRecord() []byte {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *GetRecordResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type UpdateRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *RecordType            `protobuf:"varint,1,opt,name=type,enum=gophkeeper.RecordType" json:"type,omitempty"`
	RecordNumber  *int64                 `protobuf:"varint,2,opt,name=record_number,json=recordNumber" json:"record_number,omitempty"`
	Record        []byte                 `protobuf:"bytes,3,opt,name=record" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRecordRequest) Reset() {
	*x = UpdateRecordRequest{}
	mi := &file_proto_gophkeeper_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRecordRequest) ProtoMessage() {}

func (x *UpdateRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRecordRequest.ProtoReflect.Descriptor instead.
func (*UpdateRecordRequest) Descriptor() ([]byte, []int) {
	return file_proto_gophkeeper_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateRecordRequest) GetType() RecordType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return RecordType_UNKNOWN
}

func (x *UpdateRecordRequest) GetRecordNumber() int64 {
	if x != nil && x.RecordNumber != nil {
		return *x.RecordNumber
	}
	return 0
}

func (x *UpdateRecordRequest) GetRecord() []byte {
	if x != nil {
		return x.Record
	}
	return nil
}

type DeleteRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *RecordType            `protobuf:"varint,1,opt,name=type,enum=gophkeeper.RecordType" json:"type,omitempty"`
	RecordNumber  *int64                 `protobuf:"varint,2,opt,name=record_number,json=recordNumber" json:"record_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRecordRequest) Reset() {
	*x = DeleteRecordRequest{}
	mi := &file_proto_gophkeeper_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRecordRequest) ProtoMessage() {}

func (x *DeleteRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRecordRequest.ProtoReflect.Descriptor instead.
func (*DeleteRecordRequest) Descriptor() ([]byte, []int) {
	return file_proto_gophkeeper_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteRecordRequest) GetType() RecordType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return RecordType_UNKNOWN
}

func (x *DeleteRecordRequest) GetRecordNumber() int64 {
	if x != nil && x.RecordNumber != nil {
		return *x.RecordNumber
	}
	return 0
}

var File_proto_gophkeeper_proto protoreflect.FileDescriptor

const file_proto_gophkeeper_proto_rawDesc = "" +
	"\n" +
	"\x16proto/gophkeeper.proto\x12\n" +
	"gophkeeper\x1a\x1bgoogle/protobuf/empty.proto\"4\n" +
	"\x0fRegisterRequest\x12!\n" +
	"\fcert_request\x18\x01 \x01(\fR\vcertRequest\"n\n" +
	"\x10RegisterResponse\x12%\n" +
	"\x0eca_certificate\x18\x02 \x01(\fR\rcaCertificate\x12-\n" +
	"\x12client_certificate\x18\x03 \x01(\fR\x11clientCertificateJ\x04\b\x01\x10\x02\"9\n" +
	"\vListRequest\x12*\n" +
	"\x04type\x18\x01 \x01(\x0e2\x16.gophkeeper.RecordTypeR\x04type\"(\n" +
	"\fListResponse\x12\x18\n" +
	"\arecords\x18\x01 \x01(\fR\arecords\"V\n" +
	"\x10AddRecordRequest\x12*\n" +
	"\x04type\x18\x01 \x01(\x0e2\x16.gophkeeper.RecordTypeR\x04type\x12\x16\n" +
	"\x06record\x18\x02 \x01(\fR\x06record\"c\n" +
	"\x10GetRecordRequest\x12*\n" +
	"\x04type\x18\x01 \x01(\x0e2\x16.gophkeeper.RecordTypeR\x04type\x12#\n" +
	"\rrecord_number\x18\x02 \x01(\x03R\frecordNumber\"m\n" +
	"\x11GetRecordResponse\x12*\n" +
	"\x04type\x18\x01 \x01(\x0e2\x16.gophkeeper.RecordTypeR\x04type\x12\x16\n" +
	"\x06record\x18\x02 \x01(\fR\x06record\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"~\n" +
	"\x13UpdateRecordRequest\x12*\n" +
	"\x04type\x18\x01 \x01(\x0e2\x16.gophkeeper.RecordTypeR\x04type\x12#\n" +
	"\rrecord_number\x18\x02 \x01(\x03R\frecordNumber\x12\x16\n" +
	"\x06record\x18\x03 \x01(\fR\x06record\"f\n" +
	"\x13DeleteRecordRequest\x12*\n" +
	"\x04type\x18\x01 \x01(\x0e2\x16.gophkeeper.RecordTypeR\x04type\x12#\n" +
	"\rrecord_number\x18\x02 \x01(\x03R\frecordNumber*D\n" +
	"\n" +
	"RecordType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\f\n" +
	"\bPASSWORD\x10\x01\x12\b\n" +
	"\x04TEXT\x10\x02\x12\a\n" +
	"\x03BIN\x10\x03\x12\b\n" +
	"\x04BANK\x10\x042O\n" +
	"\x06Public\x12E\n" +
	"\bRegister\x12\x1b.gophkeeper.RegisterRequest\x1a\x1c.gophkeeper.RegisterResponse2\x8c\x03\n" +
	"\aPrivate\x12;\n" +
	"\aListAll\x12\x16.google.protobuf.Empty\x1a\x18.gophkeeper.ListResponse\x129\n" +
	"\x04List\x12\x17.gophkeeper.ListRequest\x1a\x18.gophkeeper.ListResponse\x12>\n" +
	"\x06Create\x12\x1c.gophkeeper.AddRecordRequest\x1a\x16.google.protobuf.Empty\x12C\n" +
	"\x04Read\x12\x1c.gophkeeper.GetRecordRequest\x1a\x1d.gophkeeper.GetRecordResponse\x12A\n" +
	"\x06Update\x12\x1f.gophkeeper.UpdateRecordRequest\x1a\x16.google.protobuf.Empty\x12A\n" +
	"\x06Delete\x12\x1f.gophkeeper.DeleteRecordRequest\x1a\x16.google.protobuf.EmptyB\x12Z\x10gophkeeper/protob\beditionsp\xe8\a"

var (
	file_proto_gophkeeper_proto_rawDescOnce sync.Once
	file_proto_gophkeeper_proto_rawDescData []byte
)

func file_proto_gophkeeper_proto_rawDescGZIP() []byte {
	file_proto_gophkeeper_proto_rawDescOnce.Do(func() {
		file_proto_gophkeeper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gophkeeper_proto_rawDesc), len(file_proto_gophkeeper_proto_rawDesc)))
	})
	return file_proto_gophkeeper_proto_rawDescData
}

var file_proto_gophkeeper_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_gophkeeper_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_gophkeeper_proto_goTypes = []any{
	(RecordType)(0),             // 0: gophkeeper.RecordType
	(*RegisterRequest)(nil),     // 1: gophkeeper.RegisterRequest
	(*RegisterResponse)(nil),    // 2: gophkeeper.RegisterResponse
	(*ListRequest)(nil),         // 3: gophkeeper.ListRequest
	(*ListResponse)(nil),        // 4: gophkeeper.ListResponse
	(*AddRecordRequest)(nil),    // 5: gophkeeper.AddRecordRequest
	(*GetRecordRequest)(nil),    // 6: gophkeeper.GetRecordRequest
	(*GetRecordResponse)(nil),   // 7: gophkeeper.GetRecordResponse
	(*UpdateRecordRequest)(nil), // 8: gophkeeper.UpdateRecordRequest
	(*DeleteRecordRequest)(nil), // 9: gophkeeper.DeleteRecordRequest
	(*emptypb.Empty)(nil),       // 10: google.protobuf.Empty
}
var file_proto_gophkeeper_proto_depIdxs = []int32{
	0,  // 0: gophkeeper.ListRequest.type:type_name -> gophkeeper.RecordType
	0,  // 1: gophkeeper.AddRecordRequest.type:type_name -> gophkeeper.RecordType
	0,  // 2: gophkeeper.GetRecordRequest.type:type_name -> gophkeeper.RecordType
	0,  // 3: gophkeeper.GetRecordResponse.type:type_name -> gophkeeper.RecordType
	0,  // 4: gophkeeper.UpdateRecordRequest.type:type_name -> gophkeeper.RecordType
	0,  // 5: gophkeeper.DeleteRecordRequest.type:type_name -> gophkeeper.RecordType
	1,  // 6: gophkeeper.Public.Register:input_type -> gophkeeper.RegisterRequest
	10, // 7: gophkeeper.Private.ListAll:input_type -> google.protobuf.Empty
	3,  // 8: gophkeeper.Private.List:input_type -> gophkeeper.ListRequest
	5,  // 9: gophkeeper.Private.Create:input_type -> gophkeeper.AddRecordRequest
	6,  // 10: gophkeeper.Private.Read:input_type -> gophkeeper.GetRecordRequest
	8,  // 11: gophkeeper.Private.Update:input_type -> gophkeeper.UpdateRecordRequest
	9,  // 12: gophkeeper.Private.Delete:input_type -> gophkeeper.DeleteRecordRequest
	2,  // 13: gophkeeper.Public.Register:output_type -> gophkeeper.RegisterResponse
	4,  // 14: gophkeeper.Private.ListAll:output_type -> gophkeeper.ListResponse
	4,  // 15: gophkeeper.Private.List:output_type -> gophkeeper.ListResponse
	10, // 16: gophkeeper.Private.Create:output_type -> google.protobuf.Empty
	7,  // 17: gophkeeper.Private.Read:output_type -> gophkeeper.GetRecordResponse
	10, // 18: gophkeeper.Private.Update:output_type -> google.protobuf.Empty
	10, // 19: gophkeeper.Private.Delete:output_type -> google.protobuf.Empty
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_gophkeeper_proto_init() }
func file_proto_gophkeeper_proto_init() {
	if File_proto_gophkeeper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gophkeeper_proto_rawDesc), len(file_proto_gophkeeper_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_gophkeeper_proto_goTypes,
		DependencyIndexes: file_proto_gophkeeper_proto_depIdxs,
		EnumInfos:         file_proto_gophkeeper_proto_enumTypes,
		MessageInfos:      file_proto_gophkeeper_proto_msgTypes,
	}.Build()
	File_proto_gophkeeper_proto = out.File
	file_proto_gophkeeper_proto_goTypes = nil
	file_proto_gophkeeper_proto_depIdxs = nil
}
